const crypto = require('crypto');
const { google } = require('googleapis');

const CALENDAR_SCOPE = 'https://www.googleapis.com/auth/calendar.events';
const EMAIL_SCOPES = ['openid', 'email'];
const TIME_ZONE = 'Asia/Kolkata';

const getOAuthClient = () => new google.auth.OAuth2(
  process.env.GOOGLE_CLIENT_ID,
  process.env.GOOGLE_CLIENT_SECRET,
  process.env.GOOGLE_REDIRECT_URI
);

const requireGoogleConfig = () => {
  if (!process.env.GOOGLE_CLIENT_ID || !process.env.GOOGLE_CLIENT_SECRET || !process.env.GOOGLE_REDIRECT_URI) {
    throw new Error('Google Calendar OAuth is not configured');
  }
};

const stateSecret = () => process.env.GOOGLE_CALENDAR_STATE_SECRET || process.env.JWT_SECRET;

const encodeState = (payload) => {
  const secret = stateSecret();
  if (!secret) throw new Error('Google Calendar state secret is not configured');
  const encoded = Buffer.from(JSON.stringify(payload)).toString('base64url');
  const signature = crypto.createHmac('sha256', secret).update(encoded).digest('base64url');
  return `${encoded}.${signature}`;
};

const decodeState = (state) => {
  const secret = stateSecret();
  if (!secret || !state || typeof state !== 'string') throw new Error('Invalid Google Calendar authorization state');
  const [encoded, signature] = state.split('.');
  const expected = crypto.createHmac('sha256', secret).update(encoded).digest('base64url');
  if (!encoded || !signature || signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) {
    throw new Error('Invalid Google Calendar authorization state');
  }
  const payload = JSON.parse(Buffer.from(encoded, 'base64url').toString('utf8'));
  if (!payload.userId || !payload.expiresAt || Date.now() > payload.expiresAt) throw new Error('Google Calendar authorization state has expired');
  return payload;
};

const generateConsentUrl = (userId) => {
  requireGoogleConfig();
  const state = encodeState({ userId: String(userId), expiresAt: Date.now() + (10 * 60 * 1000), nonce: crypto.randomBytes(16).toString('hex') });
  return getOAuthClient().generateAuthUrl({
    access_type: 'offline',
    prompt: 'consent',
    scope: [CALENDAR_SCOPE, ...EMAIL_SCOPES],
    state,
  });
};

const exchangeCode = async (code) => {
  requireGoogleConfig();
  const client = getOAuthClient();
  const { tokens } = await client.getToken(code);
  if (!tokens.refresh_token) throw new Error('Google did not return a refresh token. Reconnect and grant consent again.');
  return { access_token: tokens.access_token, refresh_token: tokens.refresh_token, expiry_date: tokens.expiry_date };
};

const getGoogleAccountEmail = async (tokens) => {
  const client = getOAuthClient();
  client.setCredentials(tokens);
  const oauth2 = google.oauth2({ version: 'v2', auth: client });
  const { data } = await oauth2.userinfo.get();
  if (!data.email) throw new Error('Unable to determine the connected Google account email');
  return data.email;
};

const getCalendar = (refreshToken) => {
  if (!refreshToken) throw new Error('Google Calendar is not connected');
  const client = getOAuthClient();
  client.setCredentials({ refresh_token: refreshToken });
  return google.calendar({ version: 'v3', auth: client });
};

const hearingEventResource = ({ hearing, legalCase, client, lawyer }) => {
  const start = new Date(hearing.hearingDate);
  const end = new Date(start.getTime() + (60 * 60 * 1000));
  const caseName = legalCase.title || 'Case';
  const clientName = client?.displayName || legalCase.clientName || 'Not specified';
  const lawyerName = [lawyer?.firstName, lawyer?.lastName].filter(Boolean).join(' ') || 'Not specified';
  const court = hearing.courtName || legalCase.courtName || 'Not specified';
  const details = [
    `Case ID: ${legalCase._id}`,
    `Client Name: ${clientName}`,
    `Lawyer Name: ${lawyerName}`,
    `Court: ${court}`,
    `Case Status: ${legalCase.status || 'Not specified'}`,
    hearing.hearingDetails ? `Hearing Details: ${hearing.hearingDetails}` : '',
    'Generated by Verdits',
  ].filter(Boolean).join('\n');
  return {
    summary: `${caseName} - Hearing`,
    description: details,
    location: court,
    start: { dateTime: start.toISOString(), timeZone: TIME_ZONE },
    end: { dateTime: end.toISOString(), timeZone: TIME_ZONE },
    reminders: { useDefault: false, overrides: [{ method: 'popup', minutes: 24 * 60 }, { method: 'popup', minutes: 60 }] },
  };
};

const createCalendarEvent = async (refreshToken, eventResource) => {
  const { data } = await getCalendar(refreshToken).events.insert({ calendarId: 'primary', requestBody: eventResource });
  return data.id;
};

const updateCalendarEvent = async (refreshToken, eventId, eventResource) => {
  await getCalendar(refreshToken).events.update({ calendarId: 'primary', eventId, requestBody: eventResource });
};

const deleteCalendarEvent = async (refreshToken, eventId) => {
  await getCalendar(refreshToken).events.delete({ calendarId: 'primary', eventId });
};

module.exports = {
  generateConsentUrl,
  decodeState,
  exchangeCode,
  getGoogleAccountEmail,
  hearingEventResource,
  createCalendarEvent,
  updateCalendarEvent,
  deleteCalendarEvent,
};
